{
 "title": "Gitlab overview",
 "description": "Monitor a Gitlab instance",
 "tags": [ "gitlab" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(gitlab_build_info,namespace)"
    }
   },
   {
    "name": "feature_category",
    "query": {
     "query": "label_values(gitlab_transaction_duration_seconds_bucket{feature_category!=\"unknown\"},feature_category)"
    }
   },
   {
    "name": "gitaly_operations",
    "query": {
     "query": "label_values(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", container=\"gitaly\"},grpc_method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gitaly's git version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_build_info{namespace=~\"$namespace\", container=\"gitaly\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitaly number of repos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitaly_total_repositories_count{namespace=\"$namespace\"}",
     "legendFormat": "{{prefix}}"
    }
   ]
  },
  {
   "title": "Webservice CPU usage",
   "type": "gauge",
   "description": "Compared to the requests",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"webservice\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidekiq CPU usage",
   "type": "gauge",
   "description": "Compared to the requests",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"sidekiq\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitaly CPU usage",
   "type": "gauge",
   "description": "Compared to the requests",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"gitaly\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitlab shell CPU usage",
   "type": "gauge",
   "description": "Compared to the requests",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"gitlab-shell\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Requests / s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(http_requests_total{namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webservice memory usage",
   "type": "gauge",
   "description": "Compared to the requests. Pod using the most",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max (sum by (pod)(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container=\"webservice\"}) / sum by (pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidekiq memory usage",
   "type": "gauge",
   "description": "Compared to the requests. Pod using the most",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max (sum by (pod)(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container=\"sidekiq\"}) / sum by (pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitaly memory usage",
   "type": "gauge",
   "description": "Compared to the requests. Pod using the most",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max (sum by (pod)(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container=\"gitaly\"}) / sum by (pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitlab-shell memory usage",
   "type": "gauge",
   "description": "Compared to the requests. Pod using the most",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max (sum by (pod)(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container=\"gitlab-shell\"}) / sum by (pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database connections",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (__name__) ({__name__=~\"gitlab_database_connection_pool.+\", __name__!=\"gitlab_database_connection_pool_connections\", __name__!=\"gitlab_database_connection_pool_size\", namespace=\"$namespace\", db_config_name=\"main\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (__name__) (gitlab_database_connection_pool_size{namespace=\"$namespace\"}) - sum by (__name__) (gitlab_database_connection_pool_connections{namespace=\"$namespace\"})",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Gitlab version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployments{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitlab-shell version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_build_info{namespace=~\"$namespace\", container=\"gitlab-shell\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In flight connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (gitlab_shell_sshd_in_flight_connections{namespace=\"$namespace\"})",
     "legendFormat": "sshd"
    },
    {
     "expr": "sum (gitlab_shell_http_in_flight_requests{namespace=\"$namespace\"})",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Number of Webservice pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{namespace=\"$namespace\", container=\"webservice\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Sidekiq pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{namespace=\"$namespace\", container=\"sidekiq\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Gitlay pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{namespace=\"$namespace\", container=\"gitaly\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Gitlab-shell pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{namespace=\"$namespace\", container=\"gitlab-shell\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidekiq's failed jobs",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (worker) (sidekiq_jobs_failed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidekiq failed jobs /s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(sidekiq_jobs_failed_total{namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidekiq's jobs repartion per max time taken (in s)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (sidekiq_jobs_queue_duration_seconds_bucket) / (max (sum by (le) (sidekiq_jobs_queue_duration_seconds_bucket{le=\"+Inf\"}))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidekiq's redis rqs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum by (urgency) (sidekiq_redis_requests_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidekiq running jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (urgency) (sidekiq_running_jobs{namespace=\"$namespace\"})",
     "legendFormat": "Urgency: {{urgency}}"
    }
   ]
  },
  {
   "title": "Sidekiq enqueued jobs / s",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum by (urgency) (sidekiq_enqueued_jobs_total{namespace=\"$namespace\"}))",
     "legendFormat": "Urgency: {{urgency}}"
    }
   ]
  },
  {
   "title": "Sidekiq failed jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sidekiq_jobs_failed_total{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache misses / s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(gitlab_cache_misses_total{namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Emails delivery attemps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_emails_delivery_attempts_total{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitlab CI active jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gitlab_ci_active_jobs_count{namespace=\"$namespace\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Gitlab CI failed jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gitlab_ci_job_failure_reasons{namespace=\"$namespace\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Gitlab CI failed jobs (stuck or timeout)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gitlab_ci_job_failure_reasons{namespace=\"$namespace\", reason=\"stuck_or_timeout_failure\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Gitlab shell -> gitaly connection status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(gitlab_shell_gitaly_connections_total{status!=\"ok\", namespace=\"$namespace\"}) or 0",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "Gitaly operation /s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(grpc_server_handled_total{namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitaly sucessful operation /s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(grpc_server_handled_total{grpc_code=~\"(OK|internal|AlreadyExists)\", namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitaly unsucessful operation /s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(grpc_server_handled_total{grpc_code!~\"(OK|internal|AlreadyExists)\", namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitaly housekeeping sucessful operation /s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(gitaly_housekeeping_tasks_total{namespace=\"$namespace\", status=\"success\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitaly housekeeping unsucessful operation /s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(gitaly_housekeeping_tasks_total{namespace=\"$namespace\", status!=\"success\"})) or 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitaly file lookups /s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(gitaly_catfile_lookups_total{namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webservice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP 5xx",
     "type": "state-timeline",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "rate(sum by (feature_category) (http_requests_total{status=~\"5.+\", namespace=\"$namespace\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP \"get\" requests duration",
     "type": "heatmap",
     "description": "GET + HEAD + OPTIONS",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum(increase(sum without (pod) (http_request_duration_seconds_bucket{namespace=\"$namespace\", method=~\"(get|head|options)\"}[$__interval]))) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP \"set\" requests duration",
     "type": "heatmap",
     "description": "POST + PUT + DELETE",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "sum(increase(sum without (pod) (http_request_duration_seconds_bucket{namespace=\"$namespace\", method!~\"(get|head|options)\"}[$__interval]))) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of requests per category",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(sum by (feature_category) (http_requests_total{namespace=\"$namespace\"} > 0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transaction cache hits /s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(sum by (feature_category) (gitlab_transaction_cache_read_hit_count_total{namespace=\"$namespace\", feature_category=~\"$feature_category\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transaction cache miss /s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(sum by (feature_category) (gitlab_transaction_cache_read_miss_count_total{namespace=\"$namespace\", feature_category=~\"$feature_category\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SQL duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "sum by (le) (increase({__name__=~\"gitlab_sql_.*duration_seconds_bucket\", namespace=\"$namespace\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Redis requests duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "sum(increase(gitlab_redis_client_requests_duration_seconds_bucket{namespace=\"$namespace\"})) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "External HTTP requests duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 63 },
     "targets": [
      {
       "expr": "sum(increase(gitlab_external_http_duration_seconds_bucket{namespace=\"$namespace\"})) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transaction latency for $feature_category",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
     "repeat": "feature_category",
     "targets": [
      {
       "expr": "sum(increase(gitlab_transaction_duration_seconds_bucket{namespace=\"$namespace\", feature_category=~\"$feature_category\"})) by (le, feature_category)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Gitaly",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gitaly connections / s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "targets": [
      { "expr": "rate(gitaly_connections_total)", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "Gitaly operation $gitaly_operations duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
     "repeat": "gitaly_operations",
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", grpc_method=\"$gitaly_operations\"})) by (le)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Gitlab shell",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP requests duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "targets": [
      {
       "expr": "sum by (le) (increase(gitlab_shell_http_request_duration_seconds_bucket{namespace=\"$namespace\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Sidekiq",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis requests duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "targets": [
      {
       "expr": "sum by (le) (increase(sidekiq_redis_requests_duration_seconds_bucket{namespace=\"$namespace\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sidekiq's job duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "targets": [
      {
       "expr": "sum by (le) (increase(sidekiq_jobs_queue_duration_seconds_bucket{namespace=\"$namespace\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sidekiq's Gitaly job duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "sum by (le) (increase(sidekiq_jobs_gitaly_seconds_bucket{namespace=\"$namespace\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sidekiq's DB job duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "targets": [
      {
       "expr": "sum by (le) (increase(sidekiq_jobs_db_seconds_bucket{namespace=\"$namespace\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sidekiq's CPU job duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "sum by (le) (increase(sidekiq_jobs_cpu_seconds_bucket{namespace=\"$namespace\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sidekiq's job completion duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "targets": [
      {
       "expr": "sum by (le) (increase(sidekiq_jobs_completion_seconds_bucket{namespace=\"$namespace\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}